inherit_from: .rubocop_todo.yml

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
